import {port_name} from '../shared/protocol'
import type { JobRequest, PortMessageFrom,PortMessageTo } from '../shared/protocol'
import { showMenu, closeMenu, createToast, ICONS, magic_icons } from './ui'
import type { MenuEntry, NavButton, ToastHandle } from './ui'
import {startInpsector} from './inspect'